### ISSUE TITLE
Usage Example?

### ISSUE THREAD

**Issue by TonisOrmisson** [hiqdev/yii2-asset-jquery-resizable-columns#1]
I would appreciate a simple usage example.

**Comment by hiqsol** [comment]
Hello!
Sorry for long answer.

I've added Usage description to README.

**Comment by TonisOrmisson** [comment]
Thank you for that!

I am running into an asset error while using this. 

I am getting an error:
NetworkError: 404 Not Found - https://example.com/web/assets/f4b328f0/jquery.resizableColumns.css"

tried it on a working project and then additionally on a clean yii2 basic. Same result. 

What I did: 

created a clean yii2-basic project via composer
added  "hiqdev/yii2-asset-jquery-resizable-columns": "dev-master" to composer.json

did composer update - this installed following packages:
bower-asset/store-js (v1.3.20)  
hiqdev/yii2-asset-store-js (0.1.0)
bower-asset/jquery-resizable-columns (0.0.1)
hiqdev/yii2-asset-jquery-resizable-columns (dev-master 24d4249)

then added to view site/about.php

```
use hiqdev\yii2\assets\JqueryResizableColumns\ResizableColumnsAsset;
ResizableColumnsAsset::register($this);
```

I see that I have the assets folder, and it has the jquery.resizableColumns.min.js file inside it, but no css file.

**Comment by hiqsol** [comment]
Here is what I have in assets folder:

``` sh
> ll web/assets/f242c179
-rw-r--r-- 1 www-data www-data   334 Sep 12 14:28 jquery.resizableColumns.css
-rw-r--r-- 1 www-data www-data 56160 Sep 12 14:28 jquery.resizableColumns.js
-rw-r--r-- 1 www-data www-data  8610 Sep 12 14:28 jquery.resizableColumns.min.js
-rw-r--r-- 1 www-data www-data 84173 Sep 12 14:28 jquery.resizableColumns.min.js.map
```

So there is jquery.resizableColumns.css in my case.

Here is what I have in composer:

``` sh
> composer show | grep jquery-resizable-columns
bower-asset/jquery-resizable-columns          0.2.3.0             
hiqdev/yii2-asset-jquery-resizable-columns    dev-master 24d4249  Yii2 asset for jQuery resizable columns
```

So, my version for bower-asset/jquery-resizable-columns is  0.2.3.0
It is very strange that you have 0.0.1 version of bower-asset/jquery-resizable-columns

Here is how you can check why you have that version:

``` sh
> composer why bower-asset/jquery-resizable-columns
hiqdev/yii2-asset-jquery-resizable-columns  dev-master  requires  bower-asset/jquery-resizable-columns (*)
```

Try this command.

**Comment by TonisOrmisson** [comment]
Seems there is a conflict with the Yii2 dependencies?

The latest yii2 basic requires:

`"yiisoft/yii2": ">=2.0.5",`

with the latest change (require v0.2.3) I end up with composer errors, among this: 
`bower-asset/jquery-resizable-columns v0.2.3 requires bower-asset/jquery >=1.9.0,<2.0.0 -> no matching package found.`

and

```
    - yiisoft/yii2 2.0.9 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> satisfiable by bower-asset/jquery[2.2.4] but these conflict with your requirements or minimum-stability.
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> satisfiable by bower-asset/jquery[2.2.4] but these conflict with your requirements or minimum-stability.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> satisfiable by bower-asset/jquery[2.2.4] but these conflict with your requirements or minimum-stability.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.9 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> satisfiable by bower-asset/jquery[2.2.4] but these conflict with your requirements or minimum-stability.
    - Installation request for yiisoft/yii2 >=2.0.5 -> satisfiable by yiisoft/yii2[2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9].

```

So as far as I understand jquery-resizable-columns requires a version of bower-asset/jquery that conflicts with latest yii2 requirements (at least >=2.0.5). 

So for now I am unable to update the latest change for version 0.2.3, composer now fails to find matching packages.

**Comment by SilverFire** [comment]
It seems that you do not have `fxp/composer-asset-plugin` installed as described in the [guide](http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-yii)? 

If I'm right - drop the `vendor` directory in your project, install `fxp/composer-asset-plugin` and run `composer install` in your project.

**Comment by TonisOrmisson** [comment]
yup... this did the trick :)
weird that I have missed this on that machine. 
Thanks anyway! Works like a charm now.
