### ISSUE TITLE
Horizontal Scrollbar

### ISSUE THREAD

**Issue by indigitale** [hiqdev/yii2-asset-jquery-resizable-columns#2]
the plugin not working with horizontal scroll bar (with a lot of columns)

http://jsfiddle.net/dha67ngs/

**Comment by SilverFire** [comment]
This repository is a wrapper for the original jQuery plugin and I am not a maintainer of that plugin.
Please, open issue in the original repository https://github.com/dobtco/jquery-resizable-columns
